<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>
        <?php
        echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/favicon.ico'))
                ->prependStylesheet($this->basePath() . '/css/style.css')
                ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css')
        ?>
        <?php
        echo $this->headScript()->prependFile($this->basePath() . '/js/html5.js', 'text/javascript', array('conditional' => 'lt IE 9',))
                ->prependFile($this->basePath() . '/js/bootstrap.min.js')
                ->prependFile($this->basePath() . '/js/jquery.min.js')
                ->prependFile($this->basePath() . '/js/jquery.placeholder.js')
        ?>
    </head>
    <body>
        <header>     
            <div class="container">
        
                <div class="navbar navbar-inverse" role="navigation">
                    <div class="datos_user container">
                        <div class="row">
                            <div class="col-md-8">
                                <div class="row">


                                    <?php if (isset($this->barUser)): ?>
                                        <div class="col-md-6 plecadatos"><strong>Bienvenido:</strong>
                                            <?php echo $this->barUser['displayName']; ?>

                                    <?php else: ?><strong>Bienvenido Ingrese su usuario y contraseña </strong>
                                        </div>
                                    <?php endif ?>


                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>        


            <div class="navbar navbar-inverse transparent" role="navigation">
                <div class="container">
                    <div class="navbar-header">
                        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                            <span class="sr-only">Toggle navigation</span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>  
                        </button>
                      
                    </div>
                    <div class="collapse navbar-collapse">
                        <ul class="nav navbar-nav">
                           

                            <?php if (isset($this->barUser)): ?>
                                    <li class="active"><a href="<?php echo $this->url('home') ?>">Inicio</a></li>
                                    <li class="active"><a href="<?php echo $this->url('home') ?>">Mis datos</a></li>
                            <?php endif; ?>

                            <?php if ($this->barUser['gid'] != 3 && isset($this->barUser)) : ?>
                                <li class="active"><a href="<?php echo $this->url('home') ?>">Productos</a></li>
                                <li class="active"><a href="<?php echo $this->url('home') ?>">Premios</a></li> 
                            <?php endif; ?>


                            <?php if ($this->barUser['gid'] == 1 && isset($this->barUser)) : ?>
                                <li class="active"><a href="<?php echo $this->url('home') ?>">Catálogo</a></li>
                                <li class="active"><a href="<?php echo $this->url('home') ?>">Promociones</a></li> 
                            <?php endif; ?>

                           
                            <?php if (!empty($this->barUser['displayName'])): ?>   
                                    <li class="active"><a href="<?php echo $this->url('zfcuser/logout') ?>"><?php echo 'Salir' ?></a></li>
                                     <h5>El id que tengo registrado en la base de datos es </h5> <?php echo $this->barUser['gid'];?>
                            <?php endif; ?>

                          
                            

                        </ul>
                    </div>
                </div>
            </div>

        </header>  
        <div class="container">
            <?php  echo $this->content; ?>
        </div>
    </body>
</html>
