<div class="main container">
<!------------------------------------------------------------------ seccion login  ---------------------------------------------------------->
    <section class="container">
        <div class="row">
            <div class="col-md-4 spaciomargin  text-center">

                        <?php if (!$this->zfcUserIdentity()): ?>
                            <?php
                            $form = $this->loginForm;
                            $form->prepare();
                            $form->setAttribute('action', $this->url('zfcuser/login'));
                            $form->setAttribute('method', 'post');
                            ?>

                            <?php echo $this->form()->openTag($form) ?>

                            <div class="contFondo">
                                <dl class="zend_form formulario">
                                    <?php echo $this->formElementErrors($form->get('identity')) ?>
                                    <dd class="loginpunt backimg1"><?php echo $this->formInput($form->get('identity')) ?></dd>
                                    <dd class="loginpunt backimg2"><?php echo $this->formInput($form->get('credential')) ?></dd>
                                            <?php if ($this->redirect): ?>
                                                <input type="hidden" name="redirect"  value="<?php echo $this->escapeHtml($this->redirect) ?>" />
                                            <?php endif ?>

                                    <div class="row">
                                        <div class="col-md-6">
                                            <dd class="text-center butsitio"><?php echo $this->formButton($form->get('submit')) ?></dd>
                                        </div>
                                    </div>    
                                </dl>
                            </div>
                            <?php echo $this->form()->closeTag() ?>
                            <?php if ($this->enableRegistration) : ?>

                                Not registered? <a href="<?php echo $this->url('zfcuser/register') . ($this->redirect ? '?redirect=' . $this->redirect : '') ?>">Sign up!</a>
                            <?php endif; ?>
                        <?php else: ?>

                            <div class="imagen">
                        <?php endif; ?>
                    </div>
                    <div class="col-md-8 spaciomargin">
                        <?php if (!$this->zfcUserIdentity()): ?>
                                         <?php $noLogueado = "display:none" ?>
                        <?php else: ?>
                                         <?php $logueado = "display:inherit;" ?>
                        <?php endif; ?>
            </div>
        </div>
    </section>
   <!------------------------------------------------------------------ end seccion login  ---------------------------------------------------------->
</div>




